### PR TITLE
Support environment contentful parameter

### PR DESCRIPTION
**Pull request by krambuhl**
Adds support for the `environment` contentful client parameter. 

Thanks for your effort on this package, it's making our next.js project much more straightforward. We appreciate your timeliness, since this update is to better support a client project. Let me know if I can do anything to make your life a little easier.

### CODE REVIEW

**Comment by waelhasan** [comment]
Hi @ryanhefner 
Thanks for the great work you are doing here, we use your package and it makes our life easier :)
But we face the same issue as @krambuhl, and it would be great if this pull request is merged, so that we can have this feature in our code

**Comment by diegopamio** [comment]
+1, this is very much needed for my project too.

**Comment by ryanhefner** [comment]
Thank @krambuhl! Sorry this took so long to get in. I hope this helps with your projects, @waelhasan and @diegopamio!

Please let me know if you run into any other issues with this package, or [`react-contentful`](https://github.com/ryanhefner/react-contentful), and I will try to be more prompt in addressing any issues you run into.

**Comment by diegopamio** [comment]
Thank you!

**Comment by diegopamio** [comment]
I'm having the issue you mentioned about contentful complaining with `No contentful context passed to <Query />`

**Comment by ryanhefner** [comment]
Hey @diegopamio, are you using `withContentful` in your `_app.x`file? That error would be due to a `Query` existing outside the `ContentfulProvider`.

**Comment by diegopamio** [comment]
Yes, I'm using `withContentful` in the `_app.js` file, like this:

```
const MyApp = ({Component, pageProps, disableShutdown}) => {
  useEffect(() => {
    const jssStyles = document.querySelector('#jss-server-side');
    if (jssStyles) {
      jssStyles.parentElement.removeChild(jssStyles);
    }
  }, []);

  const {data, error, fetched, loading} = useContentful({
    contentType: 'Page',
    query: {
      contentType: 'recurrentInteraction',
      id: '2qAa1JM13xNcOVOy5X0rAT',
    }
  });
  return <>
    <ThemeProvider theme={theme}>
      <FullStory org={ORG_ID}/>
      <CssBaseline/>
      {
        (!data) && (
          <div>
            <div>Error retrieving contentful data</div>
            <div>
              error:
              {error || 'null'}
            </div>
          </div>
        ) ||
        (data) || (
          <>
            <Head>
              <title>{data.fields.siteTitle || 'Global IT Burnout Index'}</title>
              <meta name="description" content={data.fields.siteDescription || 'Global IT Burnout Index'}/>
              <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width"/>
            </Head>
            <Component {...pageProps} contentfulData={data} disableShutdown={disableShutdown}/>
          </>)
      };
      )}
    </ThemeProvider>
  </>;

};

const witGAApp = withGA('UA-156049947-1', Router)(MyApp);

export default withContentful({
  accessToken, host, space, environment,
})(witGAApp);

```

Is that an invalid combination? How could I achieve having the top query otherwise? Thanks!

**Comment by ryanhefner** [comment]
Ah, interesting, yeah that won't work since right now only the returned tree is being wrapped in the `ContentfulProvider`, so there is no context available for `useContentful` in `MyApp`.

I suppose you could take all the data dependent stuff and move it into its own component, and pass the relevant `_app` props into it, kind of like a `Layout` component or something. Let me know if that works/makes sense.

**Pull request merged**
